FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1

RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean


WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [“streamlit”, “run”, “app.py”, “—server.port=8501”, “—server.address=0.0.0.0”]

